/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mbot_imu_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float gyro[];
    public float accel[];
    public float mag[];
    public float tb_angles[];
    public float temp;
 
    public mbot_imu_t()
    {
        gyro = new float[3];
        accel = new float[3];
        mag = new float[3];
        tb_angles = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2e9f8f63a10a11c1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.mbot_imu_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.mbot_imu_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.gyro[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.mag[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.tb_angles[a]); 
        }
 
        outs.writeFloat(this.temp); 
 
    }
 
    public mbot_imu_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mbot_imu_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.mbot_imu_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.mbot_imu_t o = new mbot_lcm_msgs.mbot_imu_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.gyro = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyro[a] = ins.readFloat();
        }
 
        this.accel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accel[a] = ins.readFloat();
        }
 
        this.mag = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.mag[a] = ins.readFloat();
        }
 
        this.tb_angles = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.tb_angles[a] = ins.readFloat();
        }
 
        this.temp = ins.readFloat();
 
    }
 
    public mbot_lcm_msgs.mbot_imu_t copy()
    {
        mbot_lcm_msgs.mbot_imu_t outobj = new mbot_lcm_msgs.mbot_imu_t();
        outobj.utime = this.utime;
 
        outobj.gyro = new float[(int) 3];
        System.arraycopy(this.gyro, 0, outobj.gyro, 0, 3); 
        outobj.accel = new float[(int) 3];
        System.arraycopy(this.accel, 0, outobj.accel, 0, 3); 
        outobj.mag = new float[(int) 3];
        System.arraycopy(this.mag, 0, outobj.mag, 0, 3); 
        outobj.tb_angles = new float[(int) 3];
        System.arraycopy(this.tb_angles, 0, outobj.tb_angles, 0, 3); 
        outobj.temp = this.temp;
 
        return outobj;
    }
 
}

