/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class planner_request_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public mbot_lcm_msgs.pose_xyt_t goal;
    public boolean require_plan;
 
    public planner_request_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5942e2809bf67451L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.planner_request_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.planner_request_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + mbot_lcm_msgs.pose_xyt_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        this.goal._encodeRecursive(outs); 
 
        outs.writeByte( this.require_plan ? 1 : 0); 
 
    }
 
    public planner_request_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public planner_request_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.planner_request_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.planner_request_t o = new mbot_lcm_msgs.planner_request_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.goal = mbot_lcm_msgs.pose_xyt_t._decodeRecursiveFactory(ins);
 
        this.require_plan = ins.readByte()!=0;
 
    }
 
    public mbot_lcm_msgs.planner_request_t copy()
    {
        mbot_lcm_msgs.planner_request_t outobj = new mbot_lcm_msgs.planner_request_t();
        outobj.utime = this.utime;
 
        outobj.goal = this.goal.copy();
 
        outobj.require_plan = this.require_plan;
 
        return outobj;
    }
 
}

