/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_path_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int path_length;
    public mbot_lcm_msgs.pose_xyt_t path[];
 
    public robot_path_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd8a57fd0b3392990L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.robot_path_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.robot_path_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + mbot_lcm_msgs.pose_xyt_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.path_length); 
 
        for (int a = 0; a < this.path_length; a++) {
            this.path[a]._encodeRecursive(outs); 
        }
 
    }
 
    public robot_path_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_path_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.robot_path_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.robot_path_t o = new mbot_lcm_msgs.robot_path_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.path_length = ins.readInt();
 
        this.path = new mbot_lcm_msgs.pose_xyt_t[(int) path_length];
        for (int a = 0; a < this.path_length; a++) {
            this.path[a] = mbot_lcm_msgs.pose_xyt_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public mbot_lcm_msgs.robot_path_t copy()
    {
        mbot_lcm_msgs.robot_path_t outobj = new mbot_lcm_msgs.robot_path_t();
        outobj.utime = this.utime;
 
        outobj.path_length = this.path_length;
 
        outobj.path = new mbot_lcm_msgs.pose_xyt_t[(int) path_length];
        for (int a = 0; a < this.path_length; a++) {
            outobj.path[a] = this.path[a].copy();
        }
 
        return outobj;
    }
 
}

