/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class wifi_data_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public String mac_address;
    public String ssid;
    public float strength;
 
    public wifi_data_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x24a240b71ffcb820L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.wifi_data_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.wifi_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.timestamp); 
 
        __strbuf = new char[this.mac_address.length()]; this.mac_address.getChars(0, this.mac_address.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.ssid.length()]; this.ssid.getChars(0, this.ssid.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeFloat(this.strength); 
 
    }
 
    public wifi_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public wifi_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.wifi_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.wifi_data_t o = new mbot_lcm_msgs.wifi_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.mac_address = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.ssid = new String(__strbuf);
 
        this.strength = ins.readFloat();
 
    }
 
    public mbot_lcm_msgs.wifi_data_t copy()
    {
        mbot_lcm_msgs.wifi_data_t outobj = new mbot_lcm_msgs.wifi_data_t();
        outobj.timestamp = this.timestamp;
 
        outobj.mac_address = this.mac_address;
 
        outobj.ssid = this.ssid;
 
        outobj.strength = this.strength;
 
        return outobj;
    }
 
}

