/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mbot_motor_command_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float trans_v;
    public float angular_v;
 
    public mbot_motor_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf40b9c36f86202d1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.mbot_motor_command_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.mbot_motor_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.trans_v); 
 
        outs.writeFloat(this.angular_v); 
 
    }
 
    public mbot_motor_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mbot_motor_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.mbot_motor_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.mbot_motor_command_t o = new mbot_lcm_msgs.mbot_motor_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.trans_v = ins.readFloat();
 
        this.angular_v = ins.readFloat();
 
    }
 
    public mbot_lcm_msgs.mbot_motor_command_t copy()
    {
        mbot_lcm_msgs.mbot_motor_command_t outobj = new mbot_lcm_msgs.mbot_motor_command_t();
        outobj.utime = this.utime;
 
        outobj.trans_v = this.trans_v;
 
        outobj.angular_v = this.angular_v;
 
        return outobj;
    }
 
}

