/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mbot_system_reset_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int slam_mode;
    public String slam_map_location;
    public boolean retain_pose;
 
    public mbot_system_reset_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa0daccf9c9736ae0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.mbot_system_reset_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.mbot_system_reset_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.slam_mode); 
 
        __strbuf = new char[this.slam_map_location.length()]; this.slam_map_location.getChars(0, this.slam_map_location.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeByte( this.retain_pose ? 1 : 0); 
 
    }
 
    public mbot_system_reset_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mbot_system_reset_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.mbot_system_reset_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.mbot_system_reset_t o = new mbot_lcm_msgs.mbot_system_reset_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.slam_mode = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.slam_map_location = new String(__strbuf);
 
        this.retain_pose = ins.readByte()!=0;
 
    }
 
    public mbot_lcm_msgs.mbot_system_reset_t copy()
    {
        mbot_lcm_msgs.mbot_system_reset_t outobj = new mbot_lcm_msgs.mbot_system_reset_t();
        outobj.utime = this.utime;
 
        outobj.slam_mode = this.slam_mode;
 
        outobj.slam_map_location = this.slam_map_location;
 
        outobj.retain_pose = this.retain_pose;
 
        return outobj;
    }
 
}

