/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class mbot_wheel_ctrl_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float left_motor_pwm;
    public float right_motor_pwm;
    public float left_motor_vel_cmd;
    public float right_motor_vel_cmd;
    public float left_motor_vel;
    public float right_motor_vel;
 
    public mbot_wheel_ctrl_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4d910a44f6e5643dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.mbot_wheel_ctrl_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.mbot_wheel_ctrl_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.left_motor_pwm); 
 
        outs.writeFloat(this.right_motor_pwm); 
 
        outs.writeFloat(this.left_motor_vel_cmd); 
 
        outs.writeFloat(this.right_motor_vel_cmd); 
 
        outs.writeFloat(this.left_motor_vel); 
 
        outs.writeFloat(this.right_motor_vel); 
 
    }
 
    public mbot_wheel_ctrl_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public mbot_wheel_ctrl_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.mbot_wheel_ctrl_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.mbot_wheel_ctrl_t o = new mbot_lcm_msgs.mbot_wheel_ctrl_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.left_motor_pwm = ins.readFloat();
 
        this.right_motor_pwm = ins.readFloat();
 
        this.left_motor_vel_cmd = ins.readFloat();
 
        this.right_motor_vel_cmd = ins.readFloat();
 
        this.left_motor_vel = ins.readFloat();
 
        this.right_motor_vel = ins.readFloat();
 
    }
 
    public mbot_lcm_msgs.mbot_wheel_ctrl_t copy()
    {
        mbot_lcm_msgs.mbot_wheel_ctrl_t outobj = new mbot_lcm_msgs.mbot_wheel_ctrl_t();
        outobj.utime = this.utime;
 
        outobj.left_motor_pwm = this.left_motor_pwm;
 
        outobj.right_motor_pwm = this.right_motor_pwm;
 
        outobj.left_motor_vel_cmd = this.left_motor_vel_cmd;
 
        outobj.right_motor_vel_cmd = this.right_motor_vel_cmd;
 
        outobj.left_motor_vel = this.left_motor_vel;
 
        outobj.right_motor_vel = this.right_motor_vel;
 
        return outobj;
    }
 
}

