"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mbot_system_reset_t(object):
    __slots__ = ["utime", "slam_mode", "slam_map_location", "retain_pose"]

    __typenames__ = ["int64_t", "int32_t", "string", "boolean"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.slam_mode = 0
        self.slam_map_location = ""
        self.retain_pose = False

    def encode(self):
        buf = BytesIO()
        buf.write(mbot_system_reset_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.slam_mode))
        __slam_map_location_encoded = self.slam_map_location.encode('utf-8')
        buf.write(struct.pack('>I', len(__slam_map_location_encoded)+1))
        buf.write(__slam_map_location_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.retain_pose))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mbot_system_reset_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mbot_system_reset_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mbot_system_reset_t()
        self.utime, self.slam_mode = struct.unpack(">qi", buf.read(12))
        __slam_map_location_len = struct.unpack('>I', buf.read(4))[0]
        self.slam_map_location = buf.read(__slam_map_location_len)[:-1].decode('utf-8', 'replace')
        self.retain_pose = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if mbot_system_reset_t in parents: return 0
        tmphash = (0xa0daccf9c9736ae0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mbot_system_reset_t._packed_fingerprint is None:
            mbot_system_reset_t._packed_fingerprint = struct.pack(">Q", mbot_system_reset_t._get_hash_recursive([]))
        return mbot_system_reset_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mbot_system_reset_t._get_packed_fingerprint())[0]

