/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mbot_lcm_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class occupancy_grid_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float origin_x;
    public float origin_y;
    public float meters_per_cell;
    public int width;
    public int height;
    public int num_cells;
    public int slam_mode;
    public String slam_map_location;
    public byte cells[];
 
    public occupancy_grid_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xae9063a42c7624cdL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mbot_lcm_msgs.occupancy_grid_t.class))
            return 0L;
 
        classes.add(mbot_lcm_msgs.occupancy_grid_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.origin_x); 
 
        outs.writeFloat(this.origin_y); 
 
        outs.writeFloat(this.meters_per_cell); 
 
        outs.writeInt(this.width); 
 
        outs.writeInt(this.height); 
 
        outs.writeInt(this.num_cells); 
 
        outs.writeInt(this.slam_mode); 
 
        __strbuf = new char[this.slam_map_location.length()]; this.slam_map_location.getChars(0, this.slam_map_location.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        if (this.num_cells > 0)
            outs.write(this.cells, 0, (int) num_cells);
 
    }
 
    public occupancy_grid_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public occupancy_grid_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mbot_lcm_msgs.occupancy_grid_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mbot_lcm_msgs.occupancy_grid_t o = new mbot_lcm_msgs.occupancy_grid_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.origin_x = ins.readFloat();
 
        this.origin_y = ins.readFloat();
 
        this.meters_per_cell = ins.readFloat();
 
        this.width = ins.readInt();
 
        this.height = ins.readInt();
 
        this.num_cells = ins.readInt();
 
        this.slam_mode = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.slam_map_location = new String(__strbuf);
 
        this.cells = new byte[(int) num_cells];
        ins.readFully(this.cells, 0, (int) num_cells); 
    }
 
    public mbot_lcm_msgs.occupancy_grid_t copy()
    {
        mbot_lcm_msgs.occupancy_grid_t outobj = new mbot_lcm_msgs.occupancy_grid_t();
        outobj.utime = this.utime;
 
        outobj.origin_x = this.origin_x;
 
        outobj.origin_y = this.origin_y;
 
        outobj.meters_per_cell = this.meters_per_cell;
 
        outobj.width = this.width;
 
        outobj.height = this.height;
 
        outobj.num_cells = this.num_cells;
 
        outobj.slam_mode = this.slam_mode;
 
        outobj.slam_map_location = this.slam_map_location;
 
        outobj.cells = new byte[(int) num_cells];
        if (this.num_cells > 0)
            System.arraycopy(this.cells, 0, outobj.cells, 0, (int) this.num_cells); 
        return outobj;
    }
 
}

