"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class omni_motor_command_t(object):
    __slots__ = ["utime", "vx", "vy", "wz"]

    __typenames__ = ["int64_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.vx = 0.0
        self.vy = 0.0
        self.wz = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(omni_motor_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.utime, self.vx, self.vy, self.wz))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != omni_motor_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return omni_motor_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = omni_motor_command_t()
        self.utime, self.vx, self.vy, self.wz = struct.unpack(">qfff", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if omni_motor_command_t in parents: return 0
        tmphash = (0xc2eb957741a918ca) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if omni_motor_command_t._packed_fingerprint is None:
            omni_motor_command_t._packed_fingerprint = struct.pack(">Q", omni_motor_command_t._get_hash_recursive([]))
        return omni_motor_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", omni_motor_command_t._get_packed_fingerprint())[0]

