"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class omni_encoder_t(object):
    __slots__ = ["utime", "aticks", "bticks", "cticks", "a_delta", "b_delta", "c_delta"]

    __typenames__ = ["int64_t", "int64_t", "int64_t", "int64_t", "int64_t", "int64_t", "int64_t"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.aticks = 0
        self.bticks = 0
        self.cticks = 0
        self.a_delta = 0
        self.b_delta = 0
        self.c_delta = 0

    def encode(self):
        buf = BytesIO()
        buf.write(omni_encoder_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqqqqq", self.utime, self.aticks, self.bticks, self.cticks, self.a_delta, self.b_delta, self.c_delta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != omni_encoder_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return omni_encoder_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = omni_encoder_t()
        self.utime, self.aticks, self.bticks, self.cticks, self.a_delta, self.b_delta, self.c_delta = struct.unpack(">qqqqqqq", buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if omni_encoder_t in parents: return 0
        tmphash = (0xe75f01352d4097d4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if omni_encoder_t._packed_fingerprint is None:
            omni_encoder_t._packed_fingerprint = struct.pack(">Q", omni_encoder_t._get_hash_recursive([]))
        return omni_encoder_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", omni_encoder_t._get_packed_fingerprint())[0]

